// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NTTMBT.Migrations
{
    [DbContext(typeof(LTQDD))]
    partial class LTQDDModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("NTTMBT.Models.NTTM428Employee", b =>
                {
                    b.Property<string>("EmployeeID")
                        .HasColumnType("TEXT");

                    b.Property<string>("LopHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeID");

                    b.ToTable("NTTM428Employee");
                });

            modelBuilder.Entity("NTTMBT.Models.NTTM428Person", b =>
                {
                    b.Property<string>("MaSinhVien")
                        .HasColumnType("TEXT");

                    b.Property<string>("LopHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaSinhVien");

                    b.ToTable("NTTM428Person");
                });

            modelBuilder.Entity("NTTMBT.Models.NTTM428Student", b =>
                {
                    b.Property<string>("CCCN")
                        .HasColumnType("TEXT");

                    b.Property<string>("LopHoc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenSinhVien")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CCCN");

                    b.ToTable("NTTM428Student");
                });
#pragma warning restore 612, 618
        }
    }
}
